version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
      - POSTGRES_DB=test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    image: amacneil/dbmate
    environment:
      - DATABASE_URL=postgres://testuser:testuser@db:5432/test_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    command: -d "/code/migrations" up
    links:
      - db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    logging:
      driver: none